"""initial schema

Revision ID: 07d420e24666
Revises: 
Create Date: 2026-09-24 14:29:14.712897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.db.base


# revision identifiers, used by Alembic.
revision: str = '07d420e24666'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'OPERATOR', 'VIEWER', name='user_role', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('airflow_connections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('environment', sa.Enum('DEV', 'STAGING', 'PROD', name='deployment_environment', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('kind', sa.Enum('LIVE', 'MOCK', name='connection_kind', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('auth_type', sa.Enum('BASIC', 'TOKEN', 'NONE', name='auth_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=True),
    sa.Column('encrypted_secret', sa.Text(), nullable=True),
    sa.Column('api_version', sa.Enum('V1', 'V2', name='api_version', native_enum=False, create_constraint=True, length=8), nullable=True),
    sa.Column('airflow_version', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('last_health_status', sa.Enum('UNKNOWN', 'HEALTHY', 'UNAUTHORIZED', 'FORBIDDEN', 'UNREACHABLE', 'TLS_ERROR', 'INVALID_ENDPOINT', 'AIRFLOW_ERROR', name='connection_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('last_health_message', sa.Text(), nullable=True),
    sa.Column('last_latency_ms', sa.Integer(), nullable=True),
    sa.Column('last_checked_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_airflow_connections_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_airflow_connections')),
    sa.UniqueConstraint('name', name=op.f('uq_airflow_connections_name'))
    )
    with op.batch_alter_table('airflow_connections', schema=None) as batch_op:
        batch_op.create_index('uq_airflow_connections_single_default', ['is_default'], unique=True, sqlite_where=sa.text('is_default = 1'), postgresql_where=sa.text('is_default = true'))

    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('actor_type', sa.Enum('USER', 'SYSTEM', name='actor_type', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_logs_actor_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('expires_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('replaced_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens'))
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('monitored_dags',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('dag_id', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('schedule_summary', sa.String(length=200), nullable=True),
    sa.Column('is_paused', sa.Boolean(), nullable=True),
    sa.Column('is_monitored', sa.Boolean(), nullable=False),
    sa.Column('is_present', sa.Boolean(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('last_synced_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['airflow_connections.id'], name=op.f('fk_monitored_dags_connection_id_airflow_connections'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_monitored_dags')),
    sa.UniqueConstraint('connection_id', 'dag_id', name=op.f('uq_monitored_dags_connection_id_dag_id'))
    )
    with op.batch_alter_table('monitored_dags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monitored_dags_connection_id'), ['connection_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitored_dags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monitored_dags_connection_id'))

    op.drop_table('monitored_dags')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('airflow_connections', schema=None) as batch_op:
        batch_op.drop_index('uq_airflow_connections_single_default', sqlite_where=sa.text('is_default = 1'), postgresql_where=sa.text('is_default = true'))

    op.drop_table('airflow_connections')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
