"""database connections

Revision ID: e675d075682a
Revises: df53ea0f2b1a
Create Date: 2026-09-27 00:52:44.289015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.db.base


# revision identifiers, used by Alembic.
revision: str = 'e675d075682a'
down_revision: Union[str, Sequence[str], None] = 'df53ea0f2b1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('database_connections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('environment', sa.Enum('DEV', 'STAGING', 'PROD', name='db_conn_environment', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('engine', sa.Enum('POSTGRESQL', 'MYSQL', name='database_engine', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('database', sa.String(length=200), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=False),
    sa.Column('encrypted_secret', sa.Text(), nullable=True),
    sa.Column('ssl_mode', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('server_version', sa.String(length=64), nullable=True),
    sa.Column('last_health_status', sa.Enum('UNKNOWN', 'HEALTHY', 'UNAUTHORIZED', 'FORBIDDEN', 'UNREACHABLE', 'TLS_ERROR', 'INVALID_ENDPOINT', 'AIRFLOW_ERROR', name='db_conn_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('last_health_message', sa.Text(), nullable=True),
    sa.Column('last_latency_ms', sa.Integer(), nullable=True),
    sa.Column('last_checked_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_database_connections_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_database_connections')),
    sa.UniqueConstraint('name', name=op.f('uq_database_connections_name'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('database_connections')
    # ### end Alembic commands ###
