"""notification channels

Revision ID: 74a06e885cae
Revises: e675d075682a
Create Date: 2026-09-27 07:44:47.618914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.db.base


# revision identifiers, used by Alembic.
revision: str = '74a06e885cae'
down_revision: Union[str, Sequence[str], None] = 'e675d075682a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_channels',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.Enum('EMAIL', 'SLACK', 'TEAMS', 'WEBHOOK', name='channel_kind', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('encrypted_secret', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_status', sa.Enum('UNKNOWN', 'OK', 'FAILED', name='channel_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('last_message', sa.Text(), nullable=True),
    sa.Column('last_used_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_notification_channels_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_channels')),
    sa.UniqueConstraint('name', name=op.f('uq_notification_channels_name'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification_channels')
    # ### end Alembic commands ###
