"""automation

Revision ID: 02bbc07025db
Revises: 9091c52de761
Create Date: 2026-09-24 21:21:01.912320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.db.base


# revision identifiers, used by Alembic.
revision: str = '02bbc07025db'
down_revision: Union[str, Sequence[str], None] = '9091c52de761'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_RESOLUTION_OLD = sa.Enum(
    'MANUAL', 'AUTO_RECOVERED',
    name='incident_resolution', native_enum=False, create_constraint=True, length=32,
)
_RESOLUTION_NEW = sa.Enum(
    'MANUAL', 'AUTO_RECOVERED', 'AUTO_REMEDIATED',
    name='incident_resolution', native_enum=False, create_constraint=True, length=32,
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automation_workflows',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('mode', sa.Enum('LIVE', 'DRY_RUN', name='workflow_mode', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('graph', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_automation_workflows_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_automation_workflows')),
    sa.UniqueConstraint('key', name=op.f('uq_automation_workflows_key'))
    )
    op.create_table('workflow_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workflow_id', sa.Uuid(), nullable=False),
    sa.Column('workflow_version', sa.Integer(), nullable=False),
    sa.Column('graph', sa.JSON(), nullable=False),
    sa.Column('incident_id', sa.Uuid(), nullable=True),
    sa.Column('trigger_event', sa.String(length=32), nullable=False),
    sa.Column('dedup_key', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'WAITING', 'COMPLETED', 'FAILED', 'CANCELLED', name='workflow_run_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('current_node', sa.String(length=100), nullable=True),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('wake_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('claimed_until', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('claimed_by', sa.String(length=200), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('finished_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_workflow_runs_incident_id_incidents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['automation_workflows.id'], name=op.f('fk_workflow_runs_workflow_id_automation_workflows'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_runs')),
    sa.UniqueConstraint('workflow_id', 'dedup_key', name=op.f('uq_workflow_runs_workflow_id_dedup_key'))
    )
    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_runs_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index('ix_workflow_runs_status_wake_at', ['status', 'wake_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_runs_workflow_id'), ['workflow_id'], unique=False)

    op.create_table('approvals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('incident_id', sa.Uuid(), nullable=True),
    sa.Column('node_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('proposed_action', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'EXPIRED', name='approval_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('expires_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('decided_by', sa.Uuid(), nullable=True),
    sa.Column('decided_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], name=op.f('fk_approvals_decided_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_approvals_incident_id_incidents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_runs.id'], name=op.f('fk_approvals_run_id_workflow_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approvals'))
    )
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approvals_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approvals_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approvals_status'), ['status'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=True),
    sa.Column('incident_id', sa.Uuid(), nullable=True),
    sa.Column('level', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='notification_level', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('read_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_notifications_incident_id_incidents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_runs.id'], name=op.f('fk_notifications_run_id_workflow_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_run_id'), ['run_id'], unique=False)

    op.create_table('workflow_steps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.String(length=100), nullable=False),
    sa.Column('node_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'WAITING', 'COMPLETED', 'FAILED', 'SKIPPED', name='workflow_step_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('port', sa.String(length=32), nullable=True),
    sa.Column('output', sa.JSON(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('started_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('finished_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_runs.id'], name=op.f('fk_workflow_steps_run_id_workflow_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_steps'))
    )
    with op.batch_alter_table('workflow_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_steps_run_id'), ['run_id'], unique=False)

    # ### end Alembic commands ###
    # Not autogenerated: allow the new AUTO_REMEDIATED resolution (CHECK constraint).
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.alter_column(
            'resolution', existing_type=_RESOLUTION_OLD, type_=_RESOLUTION_NEW,
            existing_nullable=True,
        )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("UPDATE incidents SET resolution = 'AUTO_RECOVERED' WHERE resolution = 'AUTO_REMEDIATED'")
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.alter_column(
            'resolution', existing_type=_RESOLUTION_NEW, type_=_RESOLUTION_OLD,
            existing_nullable=True,
        )
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_steps_run_id'))

    op.drop_table('workflow_steps')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_run_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_incident_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))

    op.drop_table('notifications')
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approvals_status'))
        batch_op.drop_index(batch_op.f('ix_approvals_run_id'))
        batch_op.drop_index(batch_op.f('ix_approvals_incident_id'))

    op.drop_table('approvals')
    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_runs_workflow_id'))
        batch_op.drop_index('ix_workflow_runs_status_wake_at')
        batch_op.drop_index(batch_op.f('ix_workflow_runs_incident_id'))

    op.drop_table('workflow_runs')
    op.drop_table('automation_workflows')
    # ### end Alembic commands ###
