"""monitor blocks

Revision ID: df53ea0f2b1a
Revises: 02bbc07025db
Create Date: 2026-09-24 23:10:16.093851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.db.base


# revision identifiers, used by Alembic.
revision: str = 'df53ea0f2b1a'
down_revision: Union[str, Sequence[str], None] = '02bbc07025db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitored_dags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('detect_failures', sa.Boolean(), server_default=sa.true(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitored_dags', schema=None) as batch_op:
        batch_op.drop_column('detect_failures')

    # ### end Alembic commands ###
