"""incidents

Revision ID: 9091c52de761
Revises: 07d420e24666
Create Date: 2026-09-24 17:22:30.264735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.db.base


# revision identifiers, used by Alembic.
revision: str = '9091c52de761'
down_revision: Union[str, Sequence[str], None] = '07d420e24666'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detection_leases',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('holder', sa.String(length=200), nullable=False),
    sa.Column('expires_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('renewed_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('name', name=op.f('pk_detection_leases'))
    )
    op.create_table('incidents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('monitored_dag_id', sa.Uuid(), nullable=False),
    sa.Column('dag_id', sa.String(length=250), nullable=False),
    sa.Column('run_id', sa.String(length=250), nullable=True),
    sa.Column('last_run_id', sa.String(length=250), nullable=True),
    sa.Column('type', sa.Enum('DAG_RUN_FAILED', 'SLA_MISSED', name='incident_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='incident_severity', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ACKNOWLEDGED', 'RESOLVED', name='incident_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('fingerprint', sa.String(length=400), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('occurred_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('first_seen_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_by', sa.Uuid(), nullable=True),
    sa.Column('acknowledged_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.Uuid(), nullable=True),
    sa.Column('resolved_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('resolution', sa.Enum('MANUAL', 'AUTO_RECOVERED', name='incident_resolution', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], name=op.f('fk_incidents_acknowledged_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['connection_id'], ['airflow_connections.id'], name=op.f('fk_incidents_connection_id_airflow_connections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['monitored_dag_id'], ['monitored_dags.id'], name=op.f('fk_incidents_monitored_dag_id_monitored_dags'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], name=op.f('fk_incidents_resolved_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incidents'))
    )
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incidents_connection_id'), ['connection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_monitored_dag_id'), ['monitored_dag_id'], unique=False)
        batch_op.create_index('ix_incidents_status_last_seen', ['status', 'last_seen_at'], unique=False)
        batch_op.create_index('uq_incidents_open_fingerprint', ['fingerprint'], unique=True, sqlite_where=sa.text("status != 'RESOLVED'"), postgresql_where=sa.text("status != 'RESOLVED'"))

    op.create_table('incident_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('event', sa.String(length=32), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_incident_events_actor_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_incident_events_incident_id_incidents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incident_events'))
    )
    with op.batch_alter_table('incident_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incident_events_incident_id'), ['incident_id'], unique=False)

    op.create_table('incident_evidence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('RUN_METADATA', 'TASK_INSTANCE', 'TASK_LOG', name='evidence_kind', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('source', sa.String(length=600), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('truncated', sa.Boolean(), nullable=False),
    sa.Column('collected_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_incident_evidence_incident_id_incidents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incident_evidence'))
    )
    with op.batch_alter_table('incident_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incident_evidence_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incident_evidence_source'), ['source'], unique=False)

    with op.batch_alter_table('monitored_dags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sla_minutes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('detection_watermark', app.db.base.UTCDateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitored_dags', schema=None) as batch_op:
        batch_op.drop_column('detection_watermark')
        batch_op.drop_column('sla_minutes')

    with op.batch_alter_table('incident_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incident_evidence_source'))
        batch_op.drop_index(batch_op.f('ix_incident_evidence_incident_id'))

    op.drop_table('incident_evidence')
    with op.batch_alter_table('incident_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incident_events_incident_id'))

    op.drop_table('incident_events')
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index('uq_incidents_open_fingerprint', sqlite_where=sa.text("status != 'RESOLVED'"), postgresql_where=sa.text("status != 'RESOLVED'"))
        batch_op.drop_index('ix_incidents_status_last_seen')
        batch_op.drop_index(batch_op.f('ix_incidents_monitored_dag_id'))
        batch_op.drop_index(batch_op.f('ix_incidents_connection_id'))

    op.drop_table('incidents')
    op.drop_table('detection_leases')
    # ### end Alembic commands ###
